### Get all
GET http://localhost:8090/api/v1/dishes/all

###Get By Name

GET http://localhost:8090/api/v1/dishes?name=Soup

### Get by Id

GET http://localhost:8090/api/v1/dishes/14
Accept: application/json

### POST

POST http://localhost:8090/api/v1/dishes
Content-Type: application/json

{
    "name": "Backed potato with chicken",
    "type": 2,
    "isActual": true
}

### POST
POST http://localhost:8090/api/v1/dishes
Content-Type: application/json

{
    "name": "Meetballs from beef and pork",
    "type": 2,
    "isActual": true
}

### POST

POST http://localhost:8090/api/v1/dishes
Content-Type: application/json

{
    "name": "Soup with fish",
    "type": 1,
    "isActual": true
}

### PUT 
PUT http://localhost:8090/api/v1/dishes/19
Content-Type: application/json

{
    "name": "Backed potato with chicken",
    "type": 2,
    "isActual": false
}

### PATCH isActual
PATCH http://localhost:8090/api/v1/dishes/19
Content-Type: application/json

{
    "isActual": true
}

### PATCH description
PATCH http://localhost:8090/api/v1/dishes/19
Content-Type: application/json

{
    "description": "Wow-wow-wonderful"
}

### PATCH name and type
PATCH http://localhost:8090/api/v1/dishes/19
Content-Type: application/json

{
    "name": "Backed potato with chicken - changed",
    "type": 1
}

### PATCH type
PATCH http://localhost:8090/api/v1/dishes/19
Content-Type: application/json

{
    "type": 2
}

### DELETE BY Id
DELETE http://localhost:8090/api/v1/dishes/25

### DELETE by name

DELETE http://localhost:8090/api/v1/dishes?name=Soup%20with%20fish

###

POST http://localhost:8090/api/v1/dishes
Content-Type: application/json

{
    "name": "Chicken soup",
    "type": 1,
    "isActual": true
}